name: CraftBall & Xefir Destiny
main: jfk.CraftBall.CraftBall
version: 1.2
authors: [nisovin, JFK]
softdepend: [MultiVerse-Core]

commands:
    craftball:
        aliases: [cb]
        permission: craftball.admin
        description: "Interface with CraftBall configuration"
        usage: "Only admins can use this."

permissions:
    craftball.admin:
        default: op
